packages:
  - packages/*
  - play

catalog:
  '@eslint/compat': ^1.3.2
  '@eslint/js': ^9.35.0
  '@sveltejs/adapter-auto': ^6.1.0
  '@sveltejs/kit': ^2.36.2
  '@sveltejs/vite-plugin-svelte': ^6.1.3
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.12
  '@types/eslint': ^9.6.1
  '@types/lodash-es': ^4.17.12
  '@types/minimist': ^1.2.5
  '@types/node': ^24.5.1
  '@types/semver': ^7.7.1
  '@typescript-eslint/eslint-plugin': ^8.44.0
  '@typescript-eslint/parser': ^8.44.0
  arctic: ^3.7.0
  chalk: ^5.6.2
  daisyui: ^5.0.50
  dotenv: ^17.2.2
  element-plus: ^2.11.3
  enquirer: ^2.4.1
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.11.0
  execa: ^9.6.0
  globals: ^16.3.0
  immer: ^11.1.3
  less: 4.4.1
  lodash-es: ^4.17.22
  minimist: ^1.2.8
  mitt: ^3.0.1
  mongodb: ^6.20.0
  on-change: ^6.0.1
  prettier: ^3.6.2
  prettier-plugin-multiline-arrays: ^4.0.3
  prettier-plugin-svelte: ^3.4.0
  prettier-plugin-tailwindcss: ^0.6.14
  semver: ^7.7.2
  svelte: ^5.38.3
  svelte-check: ^4.3.1
  tailwindcss: ^4.1.12
  tsup: ^8.5.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  typescript-eslint: ^8.44.0
  unplugin-auto-import: ^20.0.0
  uuid: ^12.0.0
  vite: ^7.1.5
  vite-plugin-dts: ^4.5.4
  vitest: ^3.2.4
  vue: ^3.5.22

catalogMode: strict

onlyBuiltDependencies:
  - esbuild
