packages:
  - packages/*

catalog:
  '@eslint/compat': ^1.3.2
  '@eslint/js': ^9.35.0
  '@types/eslint': ^9.6.1
  '@types/node': ^24.3.1
  '@typescript-eslint/eslint-plugin': ^8.44.0
  '@typescript-eslint/parser': ^8.44.0
  dotenv: ^17.2.2
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  globals: ^16.3.0
  less: ^4.4.1
  prettier: ^3.6.2
  prettier-plugin-multiline-arrays: ^4.0.3
  tsup: ^8.5.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  typescript-eslint: ^8.44.0
  unplugin-auto-import: ^20.1.0
  uuid: ^12.0.0
  vite: ^7.1.5
  vite-plugin-dts: ^4.5.4

onlyBuiltDependencies:
  - esbuild
